### ISSUE TITLE
Revisit definition of special genes in Genome class

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#105]
Currently, special genes (input and output nodes and unused/non-coding genes are defined as global variables in `gp/genome.py` and then defined as class instance members of the `Genome` class.
We should revisit whether this construction is the best possible way and whether the current scheme (-1, -2, -3) is necessary.

@jakobj 's comment:

> shouldn't we just introduce InputNode and OutputNode as always-present members of Primitives that would hence have function id 0 and 1 respectively? The numbering for all other nodes would then start at 2. this seems more natural, doesn't it? and we would need only one magic number of unused gene (which i would prefer to call "non-coding gene" btw ;) )

**Comment by jakobj** [comment]
i think we should leave this as is. it's easier to read than to mentally translate function id 0 to `InputNode` all the time. if you don't have strong opinions @mschmidt87 i'd close this as won't fix.

**Comment by mschmidt87** [comment]
That is fine with me. However, what about this aspect
"Shouldn't we just introduce InputNode and OutputNode as always-present members of Primitives?"

**Comment by jakobj** [comment]
yes, it seems reasonable, but i don't see any compelling reason to do so now. is there any advantage that i'm missing? it would simplify code in `CartesianGraph` minimally, but would require substantial changes in the test suite. cost-benefit wise i'd leave as is until we have a good reason to change this.

**Comment by mschmidt87** [comment]
The only advantage would be that a user cannot forget to add the `InputNode` and `OutputNode` to `Primitives`, right?
It's a minor point, though.

**Comment by jakobj** [comment]
well, users anyway don't have to add those, it's all handled automatically. closing for now. can reopen if necessary.
