### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#121]
Due to API changes the examples are currently broken and should be fixed.

**Comment by mschmidt87** [comment]
Which PR introduced that?

**Comment by jakobj** [comment]
i think just #110 as the primitives can't be defined as a list any more. is there a way we can check examples in travis?

**Comment by mschmidt87** [comment]
Sure, we could just run them in the pipeline.

**Comment by jakobj** [comment]
and if the break travis would detect that bc of non-zero exit code? that would be great, i'll create an issue for that
