### ISSUE TITLE
Number of mutations should not be fixed to average

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#124]
By definition each gene has a certain probability of mutation, leading to a binomial distribution for the number of mutations per individual per generation. Instead of deciding for each gene whether it should be mutated, we calculate the number of mutations in advance, currently just using the average of the distribution (https://github.com/Happy-Algorithms-League/hal-cgp/blob/master/cgp/individual.py#L51) as pointed out by @HenrikMettler. A reasonable fix would be to draw the number of mutations from the correct distribution.

What do you think @mschmidt87?

**Comment by mschmidt87** [comment]
Yeo, I agree. To be honest, I always found this a bit strange.

**Comment by jakobj** [comment]
great. @HenrikMettler do you want to give this a try?

**Comment by HenrikMettler** [comment]
Yes, I will. How would you parameterize the distribution? As a binomial
with p=mut_rate and n=num_genes?

Am Fr., 29. Mai 2020 um 13:25 Uhr schrieb Jakob Jordan <
notifications@github.com>:

**Comment by jakobj** [comment]
yes, exactly, i would just use https://numpy.org/devdocs/reference/random/generated/numpy.random.binomial.html. please also add a corresponding test. maybe even start with the test (https://en.wikipedia.org/wiki/Test-driven_development) ;)
