### ISSUE TITLE
Simplify `Individual`

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#125]
`Individual` is just a thin wrapper around `Genome` which in addition carries fitness and an individual index to track the evolution. The implementation should reflect this, i.e., all functions should be implemented in `Genome` rather than in `Individual` (e.g., `mutate`).

What do you think @mschmidt87 ?

**Comment by mschmidt87** [comment]
Yes, I agree. It is confusing at the moment that there is `IndividualBase._mutate_genome` and `Genome.mutate`. This should be both in the genome, if possible, in one function.
