### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#150]
What about renaming our main branch from `master` to `main`?
See here: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

and here: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by jakobj** [comment]
sure, why not if it's easy enough. my muscle memory will adapt at some point ;)
