### ISSUE TITLE
Simplify definition of nodes

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#165]
There is a lot of duplicate code accumulating in `node.py`. Can we find a simpler, more compact way to define node operations that can be translated to the different compilation options (numpy, sympy etc) behind the scenes? It would be great if the definition of, for example, the addition and parameter nodes would reduce to this:
```python
class Add(Node):
    _output = "x_0 + x_1"

class Parameter(ParametrizedNode):
    _parameters = "p"
    _output = "p"
```

It's possible that we'll need to introduce new subclasses of `Node` such as `UnaryNode`, `BinaryNode` etc to implement this cleanly.

This would also allow us to easily add new compilation options without touching the definition of every single `Node` subclass.

**Comment by mschmidt87** [comment]
I think it would be really nice to organize the `Node` classes into a hierarchical structure. I am not sure how to realize a scenario from your code snippet, though. How would these strings be parsed?
