### ISSUE TITLE
Issue warning when `mutation_rate` is high and `mutate` potentially takes long

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#172]
#157 made sure that exactly the correct number of mutations occurs in a genome by checking that the mutated genome differs from the original one in `n_mutations` position. when using a high mutation rate and small number of primitives, this can lead to a long runtime for `mutate` as it struggles to find positions in the genome to mutate and alternative genes to insert. we should figure out exactly under which conditions this tends to occur and issue a user warning when we detect such a situation.

@HenrikMettler, since you're already familiar with that part of the code, maybe you want to look into this?

**Comment by jakobj** [comment]
btw, an alternative solution to this problem would be to have a maximum number iterations in the while loop (https://github.com/Happy-Algorithms-League/hal-cgp/blob/master/cgp/genome.py#L377) and return even if the desired number of differences was not reached while issuing a warning to the user

**Comment by HenrikMettler** [comment]
What about keeping track of the genes that were previously mutated and only allowing `gene_idx` to take different values?

**Comment by mschmidt87** [comment]
Perhaps I am missing something here, but won't this problem go away once we finally fix the current implementation to not apply a fixed number of mutations but rather mutate each gene with a fixed probability, as the variable names suggest, i.e. once #124 is closed?

**Comment by HenrikMettler** [comment]
Actually #124 (sorry I will do a PR soonish) only calculates a different `n_mutations` for every individual in every generation (from a binomial distribution). It does not apply a mutation with a probability to every single gene (this would be computationally more expensive I think). So the `while` loop in `Genome.mutate` still looks the same, just with different values for `n_mutations`

**Comment by mschmidt87** [comment]
I doubt that making a coin flip for each gene in each individual is slower. 
For instance, running this code:

```python
import numpy as np
import time

n_individuals = 10
n_genes = 15

p = 0.2

t0 = time.time()
for i in range(1000):
    np.random.binomial(n_genes, p, size=n_individuals)

print(f"Binomial took {time.time() - t0} seconds.")

t0 = time.time()
for i in range(1000):
    indx = np.random.rand(n_individuals, n_genes) < p

print(f"Bernoulli took {time.time() - t0} seconds.")
```

gives me:
```
Binomial took 0.0036504268646240234 seconds.
Bernoulli took 0.002948284149169922 seconds.
```

**Comment by jakobj** [comment]
yes, it seems like you are right @mschmidt87, my intuition would've been with @HenrikMettler, oh well this is why one should always benchmark :flushed:

however, i don't think checking every gene individually would remove the fundamental problem that we would need to detect if a user wants to modify more genes than could actually be changed. two things can happen otherwise: i) we have an infinite loop ii) the effective mutation rate is smaller than the one requested by the user without them noticing.

one suggestion to resolve this (just discussed with @HenrikMettler) would be to determine the set of all "mutable genes", make sure that set is larger than `n_mutations`, and then pick `n_mutations` genes from that set to actually be mutated. a PR will follow

**Comment by mschmidt87** [comment]
If I understand correctly, there are several types of genes that cannot be mutated:
- input region: no gene can be mutated
- output region: function gene and is_active_input gene cannot be mutated

Thus, the number of mutable genes in a genome is `len(genome) - n_immutable_genes`. This leads to a problem if the user understand `mutation_rate` as determining the number of mutated genes by doing `n_mutations = int(mutation_rate * len(self.dna))`. This is what we're doing now and how it is documented. If we do it like that, then we need to add additional checks etc.

However, if `mutation_rate` is understood as the probability for each mutable gene to be mutated, then these problems just go away. We can simply do:
```python
## is_mutable = array of length len(dna) with True/False for each gene
mutated_idx = np.where(np.logical_and(np.random.rand(len(dna)) < p, is_mutable))
dna[mutated_idx] = rng.choice(permissible_inputs, size=len(mutated_idx))
```

**Comment by jakobj** [comment]
I agree with your analysis and (of course short ;)) implementation. i would like to add that for some parameter configurations there might be only one option for a gene, which makes it questionable whether replacing this gene with itself should be counted as a mutation or not.

that being said, I think the two approaches (calculating the total number of mutations once as `n_mutations = int(mutation_rate * len(self.dna))` or mutating each gene with a certain probability) are identical as long as we count trying to mutate an gene that can not be mutated (as in your definition above) as a successful mutation. in both cases, the number of genes that are different between parent and offspring will be smaller than expected based on the total number of genes and the mutation rate.

after this discussion and considering the implementation i'm starting to like this version a bit better, however the issue remains that adopting this version offsprings can be generated _which are genetically identical to their parents_. as we rely on mutations to drive search this null operation seems wasteful to me, but from quickly scanning other implementations it seems quite common. this might be related to, as you said, this interpretation of the mutation rate being easier to explain/understand.

@HenrikMettler do you have any strong feelings either way? i mean besides having already working code for one ;)

**Comment by HenrikMettler** [comment]
I don't, given that computationally there seems to be no significant difference. (I vaguely remember reading somewhere in the literature that there is one, so I will quickly check again - but probably it is just my memory fooling me)

I would just argue that for the `permissible_inputs` we do: 
`permissible_inputs = self._permissible_inputs()
permissible_inputs.remove(dna[idx] `

Since a gene for which this list is empty (eg. a hidden gene, that can only have one possible input, in a specific graph structure) it should be that: `is_mutable = false`  I would do this before defining which elements should be mutated

**Comment by mschmidt87** [comment]
> which makes it questionable whether replacing this gene with itself should be counted as a mutation or not.

In the approach that I'm suggesting we're not counting any mutations. We're just distinguishing mutable from immutable genes, so perhaps we could label such genes as immutable (I think that is what @HenrikMettler is suggesting), but I don't actually think that that is even necessary.

> are identical as long as we count trying to mutate an gene that can not be mutated (as in your definition above) as a successful mutation

I think we're on the same page but just for clarification: In my code above, the immutable genes are excluded (because `is_mutable` would be `False` for them), so I am not sure what you mean by your sentence. 

> in both cases, the number of genes that are different between parent and offspring will be smaller than expected based on the total number of genes and the mutation rate.

This is the point: The user should not consider the total number of genes, only the total number of *mutable* genes. We shoud make the difference clear in the docstring of the function.

@HenrikMettler : This could only occur in specific graph structures, e.g. when you only have one row in the cartesian graph or something like that, right? Are you saying that we should exclude such genes for performance reasons?

**Comment by HenrikMettler** [comment]
1) Yes. 2) Rather because they can not be mutated. My understanding of a mutation is that it must change the element, eg: 
```
# self.dna[idx] = 1
possible_values = [1,2,3]
possible_values_after_mutation = [2,3]
```
Below is a mutation function that would work with this: 
```
    def mutate(self, mutation_rate: float, rng: np.random.RandomState):
        graph = CartesianGraph(self)
        active_regions = graph.determine_active_regions()
        dna = list(self._dna)
        only_silent_mutations = True

        for gene_idx, gene in enumerate(self.dna):

            p = np.random.random_sample()
            silent = True

            if p > mutation_rate:
                continue  # this gene is not mutated
            else:
                region_idx = gene_idx // self._length_per_region
                permissible_values = self._determine_permissible_values(gene_idx, gene, region_idx)
                if not len(permissible_values) == 0:
                    dna[gene_idx] = np.random.choice(permissible_values)
                    silent = region_idx not in active_regions

            only_silent_mutations = only_silent_mutations and silent

        self.dna = dna
        return only_silent_mutations
```
The separation between different types of genes and functions is done in `_determine_permissible_values`
```
    def _determine_permissible_values(
        self, gene_idx: int, gene: int, region_idx: int
    ) -> List[int]:

        if self._is_input_region(region_idx):
            return []

        elif self._is_hidden_region(region_idx):
            if self._is_function_gene(gene_idx):
                permissible_values = self._primitives
            else:
                assert self._is_hidden_input_gene(gene_idx, region_idx)
                permissible_values = self._permissible_inputs(region_idx)
            permissible_values.remove(gene)  # remove the current gene from list of permissible inputs

        else:
            assert self._is_output_region(region_idx)
            input_index = gene_idx % self._length_per_region  # assumes that the second gene in the output is the address of the input
            if input_index == 1:
                permissible_values = self._permissible_inputs_for_output_region()
                permissible_values.remove(gene)
            else:
                permissible_values = []

        return permissible_values
```

Would you be fine with this logic? 

(I can't make a PR yet, since there is a problem with removing the gene when the permissible values are the primitives & quite some tests would need adaptation...)

**Comment by jakobj** [comment]
> > which makes it questionable whether replacing this gene with itself should be counted as a mutation or not.
> 
> In the approach that I'm suggesting we're not counting any mutations. We're just distinguishing mutable from immutable genes, so perhaps we could label such genes as immutable (I think that is what @HenrikMettler is suggesting), but I don't actually think that that is even necessary.

i also don't think it's necessary to label them as immutable.
 
> > are identical as long as we count trying to mutate an gene that can not be mutated (as in your definition above) as a successful mutation
> 
> I think we're on the same page but just for clarification: In my code above, the immutable genes are excluded (because `is_mutable` would be `False` for them), so I am not sure what you mean by your sentence.

yes, we're on the same page. my sentence was actually referring to the other, not your implementation.

> > in both cases, the number of genes that are different between parent and offspring will be smaller than expected based on the total number of genes and the mutation rate.
> 
> This is the point: The user should not consider the total number of genes, only the total number of _mutable_ genes. We shoud make the difference clear in the docstring of the function.

yeah. i might be concerned about something that never occurs in practice. let's make this clear in the docstring. :ok_hand: 

> 
> @HenrikMettler : This could only occur in specific graph structures, e.g. when you only have one row in the cartesian graph or something like that, right? Are you saying that we should exclude such genes for performance reasons?

this will, for example, always occur for input genes in the first column in a graph with one input node. i am sure there are other cases.

**Comment by jakobj** [comment]
>  1. Yes. 2) Rather because they can not be mutated. My understanding of a mutation is that it must change the element, eg:
> [snip]

as far as i understand your implementation, a gene that could only be replaced with itself is never modified and genes for which more than one option exist are switched to a different allele with probability `mutation_rate`. is this correct? this seems easy enough to explain, so it would be fine with me :) tests will require a bit of thought as it may not be trivial to predict the number of mutations with this implementation.

it should be noted that this algorithm has (at least) complexity O(len(dna)) as we need to iterate over all genes. this is in contrast to an approach where we randomly generate specific indices of the dna to modify based on the expected number of mutations. as i don't think this is currently a limiting factor i don't think we need to be concerned about it for now.

**Comment by HenrikMettler** [comment]
> as far as i understand your implementation, a gene that could only be replaced with itself is never modified and genes for which more than one option exist are switched to a different allele with probability `mutation_rate`. is this correct?

Yes. 

>  tests will require a bit of thought as it may not be trivial to predict the number of mutations with this implementation.

One possibility would be to generate a large population, mutate every indiviudal, and check the mean of the number of mutations, which should be ~= mutation_rate*n_mutable_genes. 


> it should be noted that this algorithm has (at least) complexity O(len(dna)) as we need to iterate over all genes. this is in contrast to an approach where we randomly generate specific indices of the dna to modify based on the expected number of mutations. as i don't think this is currently a limiting factor i don't think we need to be concerned about it for now.

The for loop above could be changed too: 
```
 selected_gene_indices = np.nonzero(np.random.rand(len(dna))< mutation_rate)
for (gene_idx, gene) in zip(selected_gene_indices, dna[selected_gene_indices])
      permissible_values = self._determine_permissible_values()
      if not len(permissible_values) == 0: 
              # do mutation
```

This way we only iterate over the relevant genes

**Comment by jakobj** [comment]
> > tests will require a bit of thought as it may not be trivial to predict the number of mutations with this implementation.
> 
> One possibility would be to generate a large population, mutate every indiviudal, and check the mean of the number of mutations, which should be ~= mutation_rate*n_mutable_genes.

exactly! but what is `n_mutable_genes`? ;) actually this was the difficulty i was referring to.

> > it should be noted that this algorithm has (at least) complexity O(len(dna)) as we need to iterate over all genes. this is in contrast to an approach where we randomly generate specific indices of the dna to modify based on the expected number of mutations. as i don't think this is currently a limiting factor i don't think we need to be concerned about it for now.
> 
> The for loop above could be changed too:
> 
> ```python
>  selected_gene_indices = np.nonzero(np.random.rand(len(dna))< mutation_rate)
> for (gene_idx, gene) in zip(selected_gene_indices, dna[selected_gene_indices])
>       permissible_values = self._determine_permissible_values()
>       if not len(permissible_values) == 0: 
>               # do mutation
> ```
> 
> This way we only iterate over the relevant genes

nice, i like this solution! still, some nitpicking: you are just pushing the for loop to the C level as i am sure `np.nonzero` iterates over the whole array. in any case should be more than fast enough for all our purposes.

**Comment by HenrikMettler** [comment]
> exactly! but what is `n_mutable_genes`? ;) actually this was the difficulty i was referring to.

Well the test would have to count those. But since we can implement a specific graph structure for the individuals in the test, we can count this number 'manually' within the test

**Comment by jakobj** [comment]
wow, i tried to back up my claim about pushing the O(len(dna)) loop to C level, but honestly, no idea what is happening here: https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/item_selection.c#L2312 let me know if you figure it out ;)

**Comment by jakobj** [comment]
> > exactly! but what is `n_mutable_genes`? ;) actually this was the difficulty i was referring to.
> 
> Well the test would have to count those. But since we can implement a specific graph structure for the individuals in the test, we can count this number 'manually' within the test

sounds good :+1:

**Comment by mschmidt87** [comment]
@HenrikMettler 's suggestion looks good to me. 
@jakobj I think your idea of first computing a set of indices of mutated genes has the same complexity, doesn't it?

**Comment by jakobj** [comment]
> @jakobj I think your idea of first computing a set of indices of mutated genes has the same complexity, doesn't it?

no, i would think it doesn't, unless the generation of a sample from the binomial distribution somehow scales with `N` :thinking:

**Comment by mschmidt87** [comment]
The complexity would be O(N) as well, since you need to loop over the set of indices of mutated genes that scales with N, don't you?

**Comment by jakobj** [comment]
you are right under the condition that the mutation probability `p` is _not_ scaled with `N`, in that case, the expectation value is `pN`. however, if one wants to keep the number of mutated genes constant for an increasing size of the genome (this is reasonable as one would like to decouple the size of the search step from the dimension of the search space) `p` would scale `~1/N` and the expectation would be constant.

**Comment by HenrikMettler** [comment]
Maybe a cool thing would be to give the user both options: Choosing either a rate (per gene) or a fix number. 
The latter would require a "mutability_check" before selecting gene indices (and selection of a fix number of genes afterwards)

The question is whether we know for every gene after initialization whether it is mutable. If so the complexity of 'mutability_check' is O(1) and that of mutation is O(n_mutations) and no longer O(len(dna)) (...i think...)

**Comment by jakobj** [comment]
hmm, for now i would suggest to only provide the `mutation_rate` option. if there is an important use case to provide the other, we can still implement it later.
