### ISSUE TITLE
Extend documentation to cover more aspects of the API and examples

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#174]
Our documentation in the readme file is very basic at the moment. We should add more aspects of the API and describe the examples. Let's collect a list of additions here:

- [x] Describe examples
- [x] Better description of local search (incl. new option to restrict it to k individuals)
- [x] Describe difference between `IndividualSingleGenome` and `IndividualMultiGenome`
- [x] Add example using `IndividualMultiGenome`
- [x]  include an example of adding a custom node
- [x] Doc page about nodes
- [x]  include an example of choosing initial values for ParameterNode

We should also discuss whether we want to switch from README-only documentation to a more advanced documentation, e.g. on readthedocs.org.

**Comment by jakobj** [comment]
it's hard for me to estimate how much work goes into setting up and maintaining something like readthedocs. if most of those docs is automatically extracted from the code and updated, e.g., upon every merged PR, then I'm all for it. if it requires a lot of manual maintenance i would prefer to just constrain ourselves to the README to avoid "dead" documentation. only well maintained docs are good docs.

regarding extending the README:
- include an example of adding a custom node
- include an example of choosing initial values for `ParameterNode`

**Comment by mschmidt87** [comment]
I think that the cost of maintaining separate documentation is not much larger than maintaining the README. However, for simplificity I would prefer to stick to the README at the moment. Thanks for the suggestions, I added them to the list.

**Comment by mschmidt87** [comment]
Via #181 , I changed my mind and think that we should have a proper documentation using sphinx. In #181 , I have set this up in a way that allows for maximal reuse of documentation from the README. After #181  is merged, I can start creating PRs to solve this issue.

**Comment by mschmidt87** [comment]
#188 adds the examples to the doc, but there are no figures from the examples in the docs. `sphinx-gallery` supports executing the scripts when building the doc and then automatically finds the figures generated from the scripts which can then be included in the documentation and as a thumbnail in the overview page of the gallery. However, in our case, executing the examples takes quite a long time, so I would refrain from that. Thus, we would need to add the figures to the repo or (and that's the best option, I think), use the figures that we anyway create in the CI. Once we host the documentation on a website, we'll generate the docs from CI and then can probably integrate that.

**Comment by jakobj** [comment]
the "examples/example_parameterized_nodes.py" script demonstrates how to define a custom node and how to initialize the parameters. hence i ticked those boxes.

**Comment by mschmidt87** [comment]
I was thinking about adding an example that just creates some new nodes and explains that in detail. Maybe I'll create a PR for that. We should also add a doc page about the nodes (general description independent from implementation).
