### ISSUE TITLE
Decide and implement hosting option for documentation

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#184]
Once #181 is merged and we have proper documentation, we want to host the documentation on a website. We could go for two options:

1. Read the docs
https://readthedocs.org/
- external service that we can easily hook to our repository
- we would end up with a URL like https://hal-cgp.readthedocs.org 

2. Github Pages
Works similar to read the docs but requires a bit more work to set it up. On the plus side, we would have a nicer URL like `hal-cgp.github.io`. Also nicely integrates with sphinx and supports versioned documentation (just like readthedocs, this a concern of mine, but it seems possible without much difficulties: https://sphinxcontrib-versioning.readthedocs.io/en/latest/github_pages.html).

My preference would be Option 2: GitHub pages. What do you think, @jakobj ?

**Comment by jakobj** [comment]
I don't have a strong opinion and would suggest you use the option that's easier to set up and maintain. Since github pages is part of github, maybe this is the more reliable option? I'm not sure what you mean by versioned documentation tough. Shouldn't the documentation anyway always be generated from each commit?

**Comment by mschmidt87** [comment]
With versioned documentation, I mean that we want to have a documentation for each release + the documentation for the current master ("latest").

**Comment by mschmidt87** [comment]
Okay, I will look into the github pages option then. If this works fine, we'll go for that.
