### ISSUE TITLE
CI takes too long because of examples

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#208]
The CI currently already takes quite a long time (~15 minutes for the longest build) which is mainly due to the examples, see the start of the discussion in #205 . This will become even worse when we add more and more examples. 

There are three possible options:

### Manual testing of examples
Instead of running examples in every execution of the CI suite, we trigger the execution of examples only just before merging a PR. Unfortunately, this would require us to manually trigger this (with some mechanism) because travis (probably) does not support any automatic mechanism (as far as I know).

### Only run examples when deploying the docs (after PR merge)
Only run the examples *after* merging the PR when we deploy the full docs. Obiously, this begs the risk that we'll have to create PRs that fix examples after they have been broken on master.

### Run examples in CI only for a minimum number of generations
Instead of running each example completely, just run it for a few generations. Essentially, we are currently just testing whether the example scripts do not crash, but we're not testing whether they converge to the desired result. I think that this is fine, but if we anyway don't check for convergence, there is actually no point to run them for the full number of generations. Instead, we could reduce the number of generations just for the sake of testing them in CI, which will dramatically reduce runtime, but still enables us to catch bugs in the script (at least most of them).
The downside is that we need to introduce some mechanism in the scripts to reduce the number of generations. The least invasive way I can come up with is to add something like
```python
if os.environ['NUM_GENERATIONS']:
    num_generations = os.environ['NUM_GENERATIONS']
evolve_params = {'max_generations': num_generations ...}
...
```
and then set the env variable in CI.

**Comment by jakobj** [comment]
i like your last suggestion, but how about reading a command line argument (with a default value) instead of an environment variable? that seems to me the most natural way, which also the user could intuitively control

**Comment by mschmidt87** [comment]
Okay, that's actually better. I came up with the env variable option, because it is more subtle, but a proper command line argument is better.

**Comment by mschmidt87** [comment]
So, I thought about this and it seems there are two options for the third suggestion, both not ideal:
- use command-line arguments via `argparse`: Definitely the better and cleaner interface for users. However, as far as I understand, `sphinx-gallery` does not have the option to parse command line arguments to example scripts (I created an issue in their repo to ask about this: https://github.com/sphinx-gallery/sphinx-gallery/issues/731)
- use the option with an env variable. Would solve the problem with sphinx-gallery, but it is not a good API.

For option 1, we could go back to running the examples manually in CI and build the docs with the `no-plot` option. This would then test the examples and building the docs without running the examples in CI. I think that's okay, but strictly speaking, we're lacking the regular test for docs + example execution in CI, then.

**Comment by mschmidt87** [comment]
FYI, I created a PR for Sphinx-gallery which would solve our problem: https://github.com/sphinx-gallery/sphinx-gallery/pull/732
Let's see how this turns out.
