### ISSUE TITLE
Only accept outcome of local search if fitness has increased

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#215]
Currently whatever changes the local search generates, the updated parameters are written into the individual and are hence going to affect the individual's fitness. We should implement a mechanism that makes sure the changes suggested by the local search are only incorporated into the genome if they do in fact increase the individual's fitness. Other strategies do not seem sensible to me.

What do you think @mschmidt87 @HenrikMettler ?

**Comment by mschmidt87** [comment]
This sounds absolutely reasonable to me.

**Comment by HenrikMettler** [comment]
Seems logical to me to. I haven't used the local search myself and therefore I don't know the full detail of the implementation. Is there something that prevents the local search from always using the same batch of samples? Or is it just something the user has to take care of via the inner objective (resp. the local search obj)?

**Comment by jakobj** [comment]
as with fitness evaluations, it's up to the user to control whether the local search is deterministic, e.g., via the seed. but even if the same batch is used, the current parameter value will influence your update. so in some parts of the parameters space this batch might lead to an increase in fitness.

actually, this worries me a little: if the local search is deterministic and we only accept the update if it increases fitness this would mean that once we reject an parameter update, we will reject all subsequent updates if the structure of the expression doesn't change. do you have an idea of how we could handle these situations? maybe we should reject such updates after all?
