### ISSUE TITLE
Simplify `example_evo_regression`

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#221]
I keep going back to this example for trying out new stuff and whenever i do, i'm annoyed by it being so unnecessarily complicated. shouldn't we view this example as the "minimal beginner example" where everything is _as simple as possible_? this would mean reducing the example to a single target function, removing the division operator to be able to remove the ugly context manager catching warnings, not using numpy , only using one input node, etc pp. i think this make it much easier to understand for someone looking at the first script using hal-cgp. also i would remove the docstrings in favor of the sphinx documentation.

what do you think @mschmidt87 @HenrikMettler ?

**Comment by mschmidt87** [comment]
I think you're right in that we need a minimal example. However, would it make sense to just create a new simpler variant of `ego_regression` as a new `example_minimal.py`?

**Comment by HenrikMettler** [comment]
@mschmidt87 's suggestions seems reasonable to me

**Comment by jakobj** [comment]
sounds good, a minimal example it is! :+1:
