### ISSUE TITLE
Controlling the Wallclock time by limiting the Number of individual evaluations

### ISSUE THREAD

**Issue by HenrikMettler** [Happy-Algorithms-League/hal-cgp#224]
Currently the evolve function is limited by the number of generations or attaining a fitness goal (`min_fitness`). However the number of generations is only loosely related to the number of fitness evaluations, since only individuals with a novel phenotype (new configuration of active genes) are evaluated. In a qualitative comparison study for cgp's evolutionary mechanisms (https://ieeexplore.ieee.org/document/6815728/?arnumber=6815728) Goldman et al. benchmark their parameter tuning on the number of fitness evaluations. I would argue that this could be a reasonable approach for us as well, since presumably in most of the implementations: 
`T(evaluating_individual) = big`
`T(calculating_genome_output) = small`
Therefore allowing the user to define a maximal number of fitness evaluations might simplify the control of a maximal simulation duration.

**Comment by mschmidt87** [comment]
Makes sense to me. This could be an additional keyword argument for the `evolve` function which can be set instead of max_generations.

**Comment by jakobj** [comment]
an additional keyword makes sense, but i wouldn't make the two exclusive: just break whenever one of the two reaches it's maximal value.
