### ISSUE TITLE
Reorder genome to reduce limitations of gene connections

### ISSUE THREAD

**Issue by HenrikMettler** [Happy-Algorithms-League/hal-cgp#225]
As stated by Goldman et al (https://ieeexplore.ieee.org/document/6815728?arnumber=6815728) the ordering of nodes in cgp adds artificial limitations to node connections. Nodes that could be connected without forming a cycle will never be connected due to their position and adjacent nodes (assuming `n_rows = 1`) can never be connect through an intermediary node. Furthermore the probability of a node being active depends largely on its position in the genome. 
A proposed method to attenuate these problems is called _Reorder_. Roughly speaking this method shuffles the genome, by assigning a new position to a node, once all the nodes it takes input from are placed earlier in the genome. 
Since their results suggest that _Reorder_ helps to reduce the number of required function evaluations (tested on some boolean problems), I propose to add it to our library.

**Comment by mschmidt87** [comment]
Could you explain the two issues ("connections of nodes are artificially restricted", "nodes being active depends on position") in more detail. It is not clear to me why that is the case.

**Comment by HenrikMettler** [comment]
- _Connections of nodes are artificially restriced_ (paraphrasing from the paper): Consider two nodes X,Y which have no dependent relationship, where X preceeds Y. Assume that X taking input from Y would lead to a good solution. Without Reorder X can never take input from Y and would therefore need "node reinvention" of a node identical to Y appearing before X (or the other way around). With Reorder the different orderings can be examined without the need for such a reinvention. 

- _Nodes being active depends on their position_: (For simplicity let's assume `levels_back = n_columns` and `n_outputs =1`) For every node that is behind the node which connects to the output, the probability of being active is 0, as long as the input gene of the output node is not mutated. Whereas for every node on the left, there is still a chance of being connected to this internal node. Generally speaking, the more to the left (closer to the input) a node is the higher its chance of being active via an (or several) indermediates (Remember that all internal nodes have the same probability of being the input of the output node). In the paper they derived the formula for the probability of a gene to be active. Where I think there should be a "+" instead of "." before the factorial.


![Goldmann_equation](https://user-images.githubusercontent.com/32355155/89186263-d184a600-d59b-11ea-878d-7c4d5e2e2be1.png)

**Comment by mschmidt87** [comment]
Thanks for the detailed explanation. That makes sense to me. How would you implement this? As an option for the evolve function?

**Comment by HenrikMettler** [comment]
Yes, I think as an option would be best. An important question is whether we apply it to the parents before creating offspring or to the offspring. In the Goldman-paper they use the "1+4" strategy (1 parent, 4 offspring) and apply it to the parent. I assume the reasoning for that is that all offspring start from the same place searching for better solutions by mutations (small deviations). 
Whether we apply it to the parent or the offspring, the parent will almost always be replaced by a reordered version of itself, since new, phenotypically identical, individuals are preferred. (The exception is the case of all offspring having mutations on active genes which lower the fitness). So the main difference is whether the offspring should all start from the same (new) location, or each from a distinct position.
