### ISSUE TITLE
__repr__ of CartesianGraph is broken by InputNode

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#232]
This code 
```python
import cgp
import numpy as np
rng = np.random.RandomState()

genome_params = {"n_inputs": 2,
        "n_outputs": 1,
        "n_columns": 3,
        "n_rows": 3,
        "levels_back": 2,
        "primitives": (cgp.Add, cgp.Sub, cgp.ConstantFloat),
    }
genome = cgp.Genome(**genome_params)
genome.randomize(rng)
g = cgp.CartesianGraph(genome)
print(g)
```
leads to
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-20-e1cdc681402c> in <module>
----> 1 print(g)

~/opt/hal-cgp/cgp/cartesian_graph.py in __repr__(self)
     53 
     54     def __repr__(self) -> str:
---> 55         return "CartesianGraph(" + str(self._nodes) + ")"
     56 
     57     def print_active_nodes(self) -> str:

~/opt/hal-cgp/cgp/node.py in __repr__(self)
     79     def __repr__(self) -> str:
     80         return (
---> 81             f"{self.__class__.__name__}(idx: {self.idx}, active: {self._active}, "
     82             f"arity: {self._arity}, inputs {self._inputs}, output {self._output})"
     83         )

AttributeError: 'InputNode' object has no attribute '_output'
```

**Comment by mschmidt87** [comment]
I don't quite understand what the `_output` is for. The `_input` signals which other nodes form the input to this particular node. However, a node does not know to which other node it projects, i.e., there is no way it can know its own `_output`, can it? Should we just remote this? @jakobj

**Comment by jakobj** [comment]
the `_output` attribute stores the actual output values of the node, not the ids of subsequent nodes. this is needed for example when directly calling the `CartesianGraph` graph object with a list of values instead of compiling it before. so i don't think we can remove `_output` entirely, but yes, i don't think it makes sense to consider it in `__repr__` .

**Comment by mschmidt87** [comment]
Okay, I see. That seems to be different than from `_input` which stores the ids of nodes that feed into the node in question. Should we rename `_output` then to avoid confusion?

**Comment by jakobj** [comment]
that's a good point, maybe some refactoring is in order. i would suggest to rename `_input` to `_input_nodes` rather than renaming `_output`.
