### ISSUE TITLE
__check_cache_consistency fails if return_value or cached_item contains -np.inf

### ISSUE THREAD

**Issue by HenrikMettler** [Happy-Algorithms-League/hal-cgp#237]
The consistency check in https://github.com/Happy-Algorithms-League/hal-cgp/blob/90afc8dcadcff8366b4f3641c47ea494f126bc51/cgp/utils.py#L13 fails in https://github.com/Happy-Algorithms-League/hal-cgp/blob/90afc8dcadcff8366b4f3641c47ea494f126bc51/cgp/utils.py#L24  if any of the values in either `return_value` or the cached values is `(-)np.inf`. 

The problem doesn't arise for np.arrays or homogenous lists, so a possible dirty fix would be to call `np.isclose` elementwise: 

```python
import numpy as np
np.isclose((np.inf, [0]),(np.inf, [0]))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in isclose
  File "/home/henrik/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 2257, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
np.isclose([np.inf, [0]],[np.inf, [0]])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in isclose
  File "/home/henrik/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 2257, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
np.isclose([-np.inf,0], [-np.inf,0])
array([ True,  True])
```

```python
if not np.all([True for elem1, elem2 in zip(return_value, cached_item["return_value"])
                    if np.all(np.isclose(elem1, elem2))]):
```

**Comment by jakobj** [comment]
hmm, just using `np.inf` doesn't lead to an error for me:
```python
In [2]: np.isclose(np.inf, np.inf)                                                                                      
Out[2]: True
```

so the problem must be indeed with compound types. what's the output signature of the function you are trying to decorate? if it's a tuple, we might indeed need to iterate over it

**Comment by HenrikMettler** [comment]
Yes it is a tuple, but i get the error as well if i use lists, where one element is float and the other is a list (the 2nd call to np.isclose above)

**Comment by jakobj** [comment]
i see. so probably everything which can not be converted to a plain numpy array. this sounds like a general problem: how to check equality of arbitrary types. i'm not sure there's a general solution, could you please check? if there is not, what are the typical use cases we care about?

maybe @mschmidt87 has some tricks up his sleeve?

**Comment by mschmidt87** [comment]
I'm confused, shouldn't objective functions, the decorator was designed for, return scalar values?

**Comment by jakobj** [comment]
i agree with @mschmidt87. maybe you could provide a motivation for why we need to allow objectives with non-scalar return values?

**Comment by HenrikMettler** [comment]
Ah yes, I see. This is my mistake, I tried using decorator on the inner-objective function
