### ISSUE TITLE
Remove coverage from CI checks

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#249]
If a PR leads to a decrease in coverage, it's currently flagged as broken, which is quite annoying and routinely ignored by us. Imho decreasing coverage does not warrant blocking a PR as I don't think coverage per se is a good measure for code quality. I would hence suggest to remove this check, such that a PR is only marked as broken if one of the travis builds fails.

@mschmidt87, you are the CI master, could you please look into this if you agree?

**Comment by mschmidt87** [comment]
I agree. To the end, I removed coveralls from the CI checks and instead enabled coveralls to post a message to the PR thread. Check out #250 to see the result.
