### ISSUE TITLE
Multi-version documentation

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#251]
We want to publish the documentation both for the release version and the latest version from master.

**Comment by mschmidt87** [comment]
After several attempts to get this working, I am giving up on trying to make this run with publishing the docs on github pages. In principle, `sphinx-multiversion` is the way to go. I can also make it run locally (kind of, keep running into issues there as well), however, making this in the CI (travis and github actions) has proven impossible (for me, at least). See #298 .

Another issue is that `sphinx-multiversion` does not seem well maintained, since the maintainer declared it "compete" (see https://github.com/sphinx-contrib/sphinxcontrib-versioning/issues/77#issuecomment-737481668) and seems to ignore Pull-requests by other developers.

Therefore, I will migrate our documentation to readthedocs which supports multiple versions.

**Comment by mschmidt87** [comment]
Reopening here, because I will redirect the link in the README to the new docs and do some maintenance behind the scenes.

**Comment by mschmidt87** [comment]
Currently, the build for 0.2.0 is failing, (I believe) because the `.readthedocs.yaml` config file is missing. I guess the only way to fix this would be to push that file to the release branch/tag. This is a bit dirty because it will alter the release retroactively, but as far as I understand, inevitable. @jakobj

**Comment by jakobj** [comment]
well, we certainly don't want to rewrite the history of the whole repo ;) one way would be to create a new, permanent 0.2.1 release branch which contains the relevant files. alternatively we could start providing multiversion doc from 0.3.0 onwards. i have a feeling 0.4.0 might not be too far in the future ;)

**Comment by mschmidt87** [comment]
No, I also thought that creating a release branch would be the best option. I would do that rather than waiting for the 0.3.0 release.
