### ISSUE TITLE
Switch from Travis CI to Github Actions

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#266]
I want to investigate switching our CI to Github Actions. Using Travis CI is very frustrating because these yaml files and their behavior on Travis is really hard to figure out. Also, Open-Source projects have become deprioritized on Travis, see e.g. this link: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by jakobj** [comment]
here's an example setup https://github.com/lkriener/yin_yang_data_set/blob/master/.github/workflows/tests.yaml seems to work fine :)
