### ISSUE TITLE
Provide default for `levels_back`

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#276]
Typically we choose `levels_back` = `n_columns`, we should hence just set this as a default.

**Comment by HenrikMettler** [comment]
Isn't this already the case? [level_back default](https://github.com/Happy-Algorithms-League/hal-cgp/blob/05fed9df8a2b1230673bbeff23c98db33e0f4b44/cgp/genome.py#L71)

**Comment by jakobj** [comment]
> Isn't this already the case? [level_back default](https://github.com/Happy-Algorithms-League/hal-cgp/blob/05fed9df8a2b1230673bbeff23c98db33e0f4b44/cgp/genome.py#L71)

yes, you are right, but this still requires the user to pass `None`. to make the user's life easier we should provide `None` here: https://github.com/Happy-Algorithms-League/hal-cgp/blob/05fed9df8a2b1230673bbeff23c98db33e0f4b44/cgp/genome.py#L33

**Comment by HenrikMettler** [comment]
Ah right, I will quickly push a PR
