### ISSUE TITLE
Using numpy arrays as inputs to generated functions

### ISSUE THREAD

**Issue by galleon** [Happy-Algorithms-League/hal-cgp#277]
Hi
Thanks for the great library !
I am new to hal-cgp and I am currently facing a strange behaviour (that might be explained by the fact that I am just starting :))
I am using the library in a kind of (complex) RL scenario to tune a heuristic.
At a given stage I got an individual from which I extract the function to calculate the fitness (min:0, the higher the better (it is bound by 2 anyway).
I do extract the function using `f = individual.to_func()`, I therefore expect it to be callable
I do transfer this function in a class until the point where I use it:
`v = self.f([m, s])[0]`
Both `m` & `s` are: 
DEBUG:root:<class 'numpy.ndarray'>
DEBUG:root:(100,)

Despite `s` having the same type and shape as `m`and `s` it seems wrong and seems empty. It does not print the first 5 values!
Is it correct to use `.to_func()` and then using `numpy` arrays ?
How is defined the dimension/shape of the output array ? (especially what happen when the function is a constant - still I am always expecting an array of the same shape.
Finally any idea why my output behaves strangely ....

**Comment by jakobj** [comment]
thanks for your question. the function generated by `to_func` only accepts a list of scalars, one per input. if you want to use numpy arrays, you should use `to_numpy`. the generated function accepts a single numpy array of dimension `(<batch_size>, <n_inputs>)`. i guess in your case `<batch_size>=100` and `<n_inputs> = 2`. you should hence be able to do the following `v = self.f(np.vstack([m, s]).T)` where `v.shape` should be `(<batch_size>, <n_outputs>)`. could you give this a try please?

**Comment by galleon** [comment]
Thanks for the quick answer.
I cannot find any reference to `batch_size` in the doc (nor in the mountain car example). Is that in `0.2` that I am using ?

**Comment by jakobj** [comment]
sorry, maybe i wasn't clear enough. with `<batch_size>` i mean the dimension of the numpy array that does _not_ match the number of inputs defined in the cartesian graph. the goal of using numpy arrays is typically to vectorize, i.e., perform identical operations on a large number of numbers. in your case i assumed you have 100 such (pairs of) numbers to which you would like to apply the function represented by the graph, don't you? note that you do not need to specify this number manually, numpy figures it on its own.

maybe examples makes this clearer. first, we use `to_func` on an individual encoding a graph with two inputs, one output. in this case `f` expects a list of two numbers and returns a list with a single number, the result of the function encoded by the graph applied to its inputs (for concreteness assume this function is adding the two inputs):
```python
>>> f = ind.to_func()
>>> f([1, 2])
[3]
```
now let's use `to_numpy`. note that you can now apply _the same function to multiple input arrays_:
```python
>>> f = ind.to_numpy()
>>> f(np.array([[1, 2], [3, 4], [5, 6]]))
np.array([[3], [7], [11]])`
```
in this case, the "batch dimension" is three as you process three input arrays simultaneously which results in three output values.

**Comment by galleon** [comment]
My use-case is slightly different my graph has really 2 inputs but those inputs are vectors (in my case some probabilities for a multi armed bandits). So my function is really something like `v = f(u1, u2)`

So if I understand correctly your message, I need to transform my 2 vectors of shape(100, ) in 100 vectors of shape(2,) and then transform the outcome.
At the end it is probably just a transposition.

Did I get it right ?

**Comment by galleon** [comment]
Another question - Would it be possible to `pickle` one function to test it outside of a more complex framework.
I tried to do it but I got 
`_pickle.PicklingError: Can't pickle <function _f at 0x13445baf0>: attribute lookup _f on cgp.cartesian_graph failed`

**Comment by jakobj** [comment]
> My use-case is slightly different my graph has really 2 inputs but those inputs are vectors (in my case some probabilities for a multi armed bandits). So my function is really something like `v = f(u1, u2)`
> 
> So if I understand correctly your message, I need to transform my 2 vectors of shape(100, ) in 100 vectors of shape(2,) and then transform the outcome.
> At the end it is probably just a transposition.
> 
> Did I get it right ?

if you mean you need to transform your two vectors of shape (100,) into a single vector of shape (100, 2) then you got it right! :)

**Comment by jakobj** [comment]
> Another question - Would it be possible to `pickle` one function to test it outside of a more complex framework.
> I tried to do it but I got
> `_pickle.PicklingError: Can't pickle <function _f at 0x13445baf0>: attribute lookup _f on cgp.cartesian_graph failed`

unfortunately this is not easily possible. the best way to extract a function is most likely to print its functional form (`print(ind.to_sympy())`) and then manually implement a python function that implements this equation.

**Comment by galleon** [comment]
> > Another question - Would it be possible to `pickle` one function to test it outside of a more complex framework.
> > I tried to do it but I got
> > `_pickle.PicklingError: Can't pickle <function _f at 0x13445baf0>: attribute lookup _f on cgp.cartesian_graph failed`
> 
> unfortunately this is not easily possible. the best way to extract a function is most likely to print its functional form (`print(ind.to_sympy())`) and then manually implement a python function that implements this equation.

Yes but doing that I am not sure I will be exactly doing the same thing your framework is doing ;-) I am ready to follow the hard path ;-)

**Comment by galleon** [comment]
> > My use-case is slightly different my graph has really 2 inputs but those inputs are vectors (in my case some probabilities for a multi armed bandits). So my function is really something like `v = f(u1, u2)`
> > So if I understand correctly your message, I need to transform my 2 vectors of shape(100, ) in 100 vectors of shape(2,) and then transform the outcome.
> > At the end it is probably just a transposition.
> > Did I get it right ?
> 
> if you mean you need to transform your two vectors of shape (100,) into a single vector of shape (100, 2) then you got it right! :) if your graph has only a single output then the output of the function will have shape (100, 1).

Hmmm to make sure we are on the same line.
`f = ind.to_numpy()`will take one numpy array as arguments and will output one numpy array.

The input will be of shape `(<batch_size>, <n_inputs>)`and the output `(<batch_size>, <n_outputs>)`

So technically the functions has `<n_inputs>`arguments

**Comment by jakobj** [comment]
> > > Another question - Would it be possible to `pickle` one function to test it outside of a more complex framework.
> > > I tried to do it but I got
> > > `_pickle.PicklingError: Can't pickle <function _f at 0x13445baf0>: attribute lookup _f on cgp.cartesian_graph failed`
> > 
> > 
> > unfortunately this is not easily possible. the best way to extract a function is most likely to print its functional form (`print(ind.to_sympy())`) and then manually implement a python function that implements this equation.
> 
> Yes but doing that I am not sure I will be exactly doing the same thing your framework is doing ;-) I am ready to follow the hard path ;-)

well, i guess the easiest option would be to pickle the individual of which you would like to save the function, the unpickle it where you need it. as far as i know we haven't tried that yet, so this will be unexplored territory.

**Comment by jakobj** [comment]
> > > My use-case is slightly different my graph has really 2 inputs but those inputs are vectors (in my case some probabilities for a multi armed bandits). So my function is really something like `v = f(u1, u2)`
> > > So if I understand correctly your message, I need to transform my 2 vectors of shape(100, ) in 100 vectors of shape(2,) and then transform the outcome.
> > > At the end it is probably just a transposition.
> > > Did I get it right ?
> > 
> > 
> > if you mean you need to transform your two vectors of shape (100,) into a single vector of shape (100, 2) then you got it right! :) if your graph has only a single output then the output of the function will have shape (100, 1).
> 
> Hmmm to make sure we are on the same line.
> `f = ind.to_numpy()`will take one numpy array as arguments and will output one numpy array.
> 
> The input will be of shape `(<batch_size>, <n_inputs>)`and the output `(<batch_size>, <n_outputs>)`
> 
> So technically the functions has `<n_inputs>`arguments

yes, the function `f` returned from `ind.to_numpy()` will take one numpy array as an argument and return a numpy array as output with the dimensions you state :+1:

**Comment by mschmidt87** [comment]
If I may chime in: I think you are talking about two different cases. If I understand @galleon correctly, his function has two inputs and each input has dimension 100, so the 100 is not the `<batch_size>` dimension, but rather his arguments to the output of `to_numpy()` would be something like: `(<batch_size>, <n_inputs>, <dim_of_each_input>)`, where `batch_size=1, n_inputs=2, dim_of_each_input=100`. Correct?
Spontaneously, I'd say this should also work with `to_func()`, but I think we haven't tried multi-dimensional inputs to a graph, i.e., in our examples `dim_of_each_input=1`, right, @jakobj ?

@galleon , could you provide a minimal code snippet to reproduce your problem? I think that would facilitate the discussion a lot.

**Comment by jakobj** [comment]
> If I may chime in: I think you are talking about two different cases. If I understand @galleon correctly, his function has two inputs and each input has dimension 100, so the 100 is not the `<batch_size>` dimension, but rather his arguments to the output of `to_numpy()` would be something like: `(<batch_size>, <n_inputs>, <dim_of_each_input>)`, where `batch_size=1, n_inputs=2, dim_of_each_input=100`. Correct?
> Spontaneously, I'd say this should also work with `to_func()`, but I think we haven't tried multi-dimensional inputs to a graph, i.e., in our examples `dim_of_each_input=1`, right, @jakobj ?

sorry for confusing everyone by talking about "batch sizes". with that name i mean the same as what you call "dimension of input". for function generated by `to_numpy` our library assumes that the first dimension is the dimension that you would like to vectorize along ("dimension of input") and the second dimension matches the number of graph inputs. see for exampel https://github.com/Happy-Algorithms-League/hal-cgp/blob/master/examples/example_piecewise_target_function.py#L63 ff. anything with more than two dimensions for `to_numpy` is untested and `to_func` has only been tested with scalars, yes.

**Comment by galleon** [comment]
@mschmidt87 you are welcome! I think you are correct in your analysis.
I have cleaned my code and make it as minimal as possible - It is here: https://github.com/galleon/curly-octo-eureka
If you have a gitter, gchat or slack ... I can point out where it hurts

**Comment by jakobj** [comment]
> I have cleaned my code and make it as minimal as possible - It is here: https://github.com/galleon/curly-octo-eureka

well, from the looks of it this https://github.com/galleon/curly-octo-eureka/blob/main/bas/submissionv3.py#L127 ff, i.e., `u = np.vstack([m, s]).T; v = self.f(u)` looks good. does it do what you expect? unfortunately i can not run your code to check.

**Comment by galleon** [comment]
It seems that my problem comes from this line:
https://github.com/galleon/curly-octo-eureka/blob/main/train_cgp.py#L114
and that I should rather use:
  individual.to_fun | or individual.to_numpy without ()
  
Any comment insight ?

**Comment by jakobj** [comment]
that line seems correct. `f` will be a function that accepts numpy arrays as inputs. what is the error message you get?

**Comment by jakobj** [comment]
@galleon has the issue been resolved? if so, we can close this issue

**Comment by galleon** [comment]
Yes that one can be closed but those notions would deserved to be tackled in the documentation.

I am still facing a problem with the library. During the first generation, my best fitness is given by:
  - t=1595.8263522479974s: new best found with score=2.1905: [x_1 - x_3]
  Later I get this message:
[2/100] max fitness: 2.04545

and then the code stops.

I know my fitness can move within [0, 4] (the best is 4) and a score of 2 is not that great ;-)

Here are my parameters:

```
population_params = {"n_parents": 10, "seed": 8188211, "mutation_rate": 0.04}

genome_params = {
    "n_inputs": 5,
    "n_outputs": 1,
    "n_columns": 12,
    "n_rows": 1,
    "levels_back": 5,
    "primitives": (
        cgp.Add,
        cgp.Sub,
        cgp.Mul,
        cgp.Div,
        cgp.Pow,
        cgp.IfElse,
        cgp.ConstantFloat,
        Exp,
        Log,
        # Cos,
        # Sin,
        Tanh,
    ),  # , Tan, Acos, Asin, Atan),
}


ea_params = {"n_offsprings": 4, "tournament_size": 1, "n_processes": 4}

evolve_params = {"max_generations": 100, "min_fitness": 2.0}
```
Am I doing something wrong ?

 Let me know if you want me to open a different issue?

**Comment by fteicht** [comment]
Hi all, thanks for the great library, indeed!
Actually I am facing the exact same issue as the one mentioned by @galleon in his last comment above.
Any clue why the `evolve` function stops after 2 iterations only with some parameters?

**Comment by jakobj** [comment]
interesting. it shouldn't ;) i would suggest you open a new issue, and please add a minimal reproducer. this makes it significantly easier for us to discover the source of the problem.

**Comment by jakobj** [comment]
closing as resolved
