### ISSUE TITLE
Rename "min_fitness" in evolve_params

### ISSUE THREAD

**Issue by HenrikMettler** [Happy-Algorithms-League/hal-cgp#289]
Given the user experience in #288 I think the variable name `min_fitness` in the `evolve_params` is confusing. I think we should rename it to sthg like `target_fitness`.

**Comment by jakobj** [comment]
hmm, interesting point. now that i think about it, shouldn't it be called `max_fitness`? it's the maximal fitness an individual can achieve before the search is stopped. i'm not sure about `target_fitness`.

**Comment by HenrikMettler** [comment]
Maybe `threshold_fitness`? I think with `max_fitness` one is tempted to use it as a maximum possible fitness, where in fact one might be happy with convergence close to the effective possilble maximum.

**Comment by mschmidt87** [comment]
An alternative would be to use something like `early_stopping_fitness`, to use a more machine learning-related term.

**Comment by jakobj** [comment]
> Maybe `threshold_fitness`? I think with `max_fitness` one is tempted to use it as a maximum possible fitness, where in fact one might be happy with convergence close to the effective possilble maximum.

i'm not sure i understand: but yes, "max fitness" would be the maximum possible fitness bc the algorithm would exit when reaching it.

> An alternative would be to use something like early_stopping_fitness, to use a more machine learning-related term.

i find this term super hard to understand. in particular "early stopping" is also used for methods that stop evaluating an individual when they perform poorly, e.g., hurdles.

**Comment by mschmidt87** [comment]
Okay, I only know the term "early stopping" in the same meaning that our current `min_fitness` employs.
I don't particularly like `max_fitness` for the same reason that @HenrikMettler mentioned.

What about `max_evolve_fitness` to reflect the fact that this is not the maximum possible fitness of the task at hand, but the maximum fitness we evolve to.

**Comment by HenrikMettler** [comment]
> i'm not sure i understand: but yes, "max fitness" would be the maximum possible fitness bc the algorithm would exit when reaching it.
> 
Not sure this is true, eg. one could set: `max_fitness = 0.99', not reached it until generation n and then suddenly have an individual with fitness '1'

**Comment by mschmidt87** [comment]
Let's make a decision here. I would personally prefer `evolve_threshold_fitness` or `evolve_stop_fitness` or `evolve_termination_fitness`.

**Comment by mschmidt87** [comment]
Anyone here?

**Comment by jakobj** [comment]
to move this ahead i can agree to `termination_fitness`. i would certainly try to avoid a `evolve_` prefix since it's an argument to the `evolve` function and that just seems a bit redundant ;)
