### ISSUE TITLE
Support Python 3.9 and drop support of python 3.6

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#303]
Python 3.9 was released more than 6 months ago, so we should make hal-cgp compatible with it. This probably doesn't require much, simply adding it to the CI might be enough.

**Comment by mschmidt87** [comment]
As it turns out, there is no scipy version that is compatible with both 3.6 and 3.9. Therefore, to support 3.9, we need to drop support for 3.6. I would suggest to do this for 0.4.0. Therefore I changed the title and the milestone.

**Comment by jakobj** [comment]
hmm, isn't it possible to determine which scipy version to install depending on the python version?

**Comment by mschmidt87** [comment]
I think it is not a good idea to introduce such conditional requirements. This is going to create issues in the future because e.g. scipy relies on numpy, so we'll have to create another condition for numpy.

Other packages have recently dropped support for Python 3.6 as well (like scipy and numpy). I don't think it is necessary to support 4 major releases, with 3.6 being more than 4 years old. What would be a reason to do that?

**Comment by jakobj** [comment]
no reason other than backward compatibility ;) i think it's fine, people should just update their python if any issues appear :+1:
