### ISSUE TITLE
Upgrade requirements to latest versions of packages

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#314]
When upgrading to the most recent numpy version, we run into a dependency issue:
```bash
hal-cgp 0.1.1 has requirement numpy~=1.18.3, but you'll have numpy 1.20.2 which is incompatible.
```

This should be fixed.

**Comment by HenrikMettler** [comment]
Would it make sense to tie every release to the newest version of the (extra-) requirements? Compability should be covered by the tests, so we could just upgrade the requirements before release.

**Comment by mschmidt87** [comment]
I agree, this sounds like a good idea. Our requirements are quite outdated.
