### ISSUE TITLE
Consistently use `objective` instead of `obj` 

### ISSUE THREAD

**Issue by HenrikMettler** [Happy-Algorithms-League/hal-cgp#336]
In some examples and tests the objective function is called `obj` instead of `objective`. This should cleaned up.

**Comment by svenkat19** [comment]
I would like to work on this. Can you pls assign it to me?

**Comment by svenkat19** [comment]
I went through the examples and test files and I found no issue in them wrt "obj" and "objective"

**Comment by HenrikMettler** [comment]
Ah yes you are right. `Obj` is only used together with `functools.partial`. Thanks for pointing this out. Closing the issue but you are very welcome to contribute on another issue :)
