### ISSUE TITLE
Fails if n_processes>1, Why ? How to solve? 

### ISSUE THREAD

**Issue by Mujtaba1986** [Happy-Algorithms-League/hal-cgp#381]
Hi, The execution becomes unstable and stuck in an infinite loop of errors if I select more than 1 in n_processes. 
ea_params = {"n_offsprings": 4, "mutation_rate": 0.03, "n_processes": 1}

How to resolve this issue ? 
Secondly, 
Does this parameter means fitness function will run in parallel on multiple core processor ? 
e.g I have 12 cores, the value of 12 will mean 12 parallel runs of fitness function?

**Comment by jakobj** [comment]
hi @Mujtaba1986 sorry for getting back to you so late. could you provide more details about the error? what exactly does `examples fail to run` mean?

**Comment by jakobj** [comment]
if the problem persists, please reopen this issue
