### ISSUE TITLE
Provide mechanisms to cache python functions/pytorch classes

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#61]
Currently the example for caching uses SymPy expressions. This makes sense since SymPy can simplify expressions, thereby identifying functionally equivalent individuals even when their genotypes and even phenotypes (unsimplified) differ. However one might want to avoid converting the cartesian graph to a sympy expressions and rather work with python functions or pytorch classes. In these cases caching would still make sense for individuals that only different in inactive genes. How could we provide such functionality most easily?

**Comment by mschmidt87** [comment]
> In these cases caching would still make sense for individuals that only different in inactive genes.

Why is that?

**Comment by jakobj** [comment]
well since these individuals differ only in inactive genes, their function is the same. one could for example get two identical torch graphs from two different genotypes if the difference is only in inactive parts of the genome. maybe one could use the function string/class string that is built during function/torch class definition to identify these?

**Comment by mschmidt87** [comment]
Sorry, I think I misunderstood the first statement. That makes total sense, of couse.

**Comment by jakobj** [comment]
ok, will look into how this could be implemented best

**Comment by jakobj** [comment]
i think it actually does not make sense to implement caching for the other `to_...` functions. i think we should rather always use the sympy-generated string. this will avoid reevaluating functions that are identical after simplification such as `x[0] + x[0]` and `2 * x[0]`. i will check how to make caching via sympy expressions easiest for the user.

**Comment by jakobj** [comment]
one option would be to always expect the first argument of the decorated objective to be an individual, so instead of `str(<first arg>)` the decorator would do `<first arg>.to_sympy(simplify=True)` (https://github.com/Happy-Algorithms-League/hal-cgp/blob/master/cgp/utils.py#L32 ff). this would be clean and easy for the user but has two drawbacks:
- decorator is less flexible (first argument *must* be an individual)
- objectives that explicitly use `to_sympy` would call it twice

i think the second one could easily be addressed by memoization inside the `Individual` instances if speed becomes an issue.

**Comment by jakobj** [comment]
there's a nice method in https://arxiv.org/abs/2003.03384: they evaluate each individual for a small number of steps and compute a hash from the result (the algorithms/comp graph "fingerprint"). this hash is checked against with a database of (hash, fitness) pairs which can return the fitness directly if a result for this specific hash exists. this approach seems more general than our current cache decorator and i would hence suggest to implement something similar which would could be applied all current `to_` functions. what do you think @mschmidt87 ?
