### ISSUE TITLE
Add more nodes

### ISSUE THREAD

**Issue by mschmidt87** [Happy-Algorithms-League/hal-cgp#93]
As an extension to the nodes currently implemented, add nodes that perform:
- comparisons:  less than (`<`) and greater than (`>`)
- if/else branches
- binary operators: AND, OR, NOT

**Comment by jakobj** [comment]
i like the idea, in particular for the larger/smaller operations i can think of an application ;)

we need to carefully think about this since i think it's not as easy as just implementing some new nodes. what are the inputs for each operator, what is the output? can we still execute the graph on the fly (`res = graph(<inputs>)`) or do we always need to generate code like in `to_func` etc? i guess it would help to start with a small example where such functionality is necessary, then develop ideas from there

**Comment by mschmidt87** [comment]
One simple application example would be to do regression with a target function that is defined differently for certain intervals, such that one needs if/else checks and "greater/less than" comparison operators.

One difficulty is that potentially the nodes would not necessarily accept each other as inputs any more. For instance, `if/else` should strictly accept only boolean as input. However, we can circumvent that as in Python, i.e. for instance cast integers to True except for 0 value.
The same applies to the binary operators.

**Comment by jakobj** [comment]
I'm not sure about accepting only particular types as inputs. Wouldn't this break with ducktyping? if we nevertheless implement this, this could, for example, be explicitly considered during mutation: only those mutations are allowed that do not make the expression invalid. I'm now wondering how this works for general GP that, for examples generates code instead of mathematical expressions. Is the generated code syntax checked only during fitness evaluation? This seems like a waste, bc i would strongly suggest that most randomly mutated programs are invalid.

**Comment by jakobj** [comment]
is there some progress on this issue @mschmidt87 ? if not i would rather close now and reopen again when this becomes relevant.

**Comment by mschmidt87** [comment]
I haven't had time to work on this, but why closing the issue? It is marked for the future and as an enhancement so I don't see why we cannot just leave it open and, if someone wants to contribute, continue the discussion.

**Comment by jakobj** [comment]
i'd just like to keep this clean by avoiding collecting issues that will not be addressed in the near future, i guess my feeling being that a project should have zero "issues" ;) can we find a different place to keep these "future enhancement ideas"?

**Comment by mschmidt87** [comment]
I would argue that this is what the #thefuture tag is for.

**Comment by mschmidt87** [comment]
Cool, sounds good. I would suggest to create the node within an example that demonstrates its application. I think, we need to discuss which nodes we should add to the catalogue of nodes and which can just live in an example. 

In this case, I would suggest to add both a comparison operator (actually, just implementing the `<` is sufficient because `>` can be trivially achieved by just swapping the input arguments) and the if/else-operator.

Then you could create an example similar to `example_evo_regression.py` but with a function like this:

```
import numpy as np
import pylab as pl

x = np.linspace(-5., 5., 100)
def f(x): 
    y = np.zeros_like(x) 
    y[x<0] = - x[x<=0] + 3. 
    y[x>0] = x[x>0]**2 
    return y 

pl.plot(x, y)
pl.show()
```
![sample](https://user-images.githubusercontent.com/6512628/88176476-4d105a00-cc62-11ea-9e5a-37954b927e48.png)

What do you think?

**Comment by mschmidt87** [comment]
By the way: With regards to valid inputs to the operators, I would just follow the usual Python ducktyping way:

The boolean operators also accept integers and floats, and just treat anything except 0 as True.

**Comment by HenrikMettler** [comment]
> In this case, I would suggest to add both a comparison operator (actually, just implementing the `<` is sufficient because `>` can be trivially achieved by just swapping the input arguments) and the if/else-operator.

Should we also have `==` as a comparison operator? 
About the if/else operator I am not sure I understand what you mean: Would you implement them with a fixed, predefined condition, eg:
 ```python
if input_gene < 0:
     out = 1 
else: 
     out = 0
```

Or how should i understand the idea?

**Comment by mschmidt87** [comment]
What I'm imagining is this:
the node receives three inputs `in0, in1, in2` and yields one output `out`
```
if in0:
    out = in1
else:
    out = in2
return out
```

**Comment by jakobj** [comment]
ughh, i'm starting to understand why people use LISP for genetic programming :D nesting functions like this does seem to be a lot easier than in Python. `if/else` should be possible for `to_func` with python's ternary operator, and sympy's `Piecewise` operator (https://docs.sympy.org/latest/modules/functions/elementary.html#piecewise), for numpy and torch this might be a bit more involved. when it comes to defining arbitrary code for operator nodes i fear the current implementation will be outgrown, but let's see :)

**Comment by jakobj** [comment]
oh look, there's also a piecewise for numpy: https://numpy.org/doc/stable/reference/generated/numpy.piecewise.html
