### ISSUE TITLE
Move parameter value storage from `Individual` to `Genome`

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#97]
The output values of `Parameter` nodes are currently stored in each individual (https://github.com/Happy-Algorithms-League/python-gp/blob/master/gp/individual.py#L33). I would argue this is rather surprising since they define the values of node encoded in the `Genome` and like it are passed on to the next generation.
I think it would hence be more natural to store these values within the `Genome`. This would also remove the need to pass around the dictionary from the `Individual` to all `to...` functions (e.g., https://github.com/Happy-Algorithms-League/python-gp/blob/master/gp/individual.py#L123).

**Comment by mschmidt87** [comment]
I think this suggestion makes sense. However, is high priority? It seems that we could postpone this to 0.2?
